// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSsPAqlvQmpoZvu6xLkjBuK3OxM_8dQhY',
    appId: '1:408689466375:web:4b86457e3c3931e8079ea2',
    messagingSenderId: '408689466375',
    projectId: 'bvyo-f3df0',
    authDomain: 'bvyo-f3df0.firebaseapp.com',
    storageBucket: 'bvyo-f3df0.firebasestorage.app',
    measurementId: 'G-C9BFC7ND7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUYmluuBsUd1a4j6AwrZ2VilWKaxu-arQ',
    appId: '1:408689466375:android:7d6098f3236e641d079ea2',
    messagingSenderId: '408689466375',
    projectId: 'bvyo-f3df0',
    storageBucket: 'bvyo-f3df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW3XtSb8kEhLSiBCRohWr6-sa9lO9H1x4',
    appId: '1:408689466375:ios:f1de2fcf4149d06d079ea2',
    messagingSenderId: '408689466375',
    projectId: 'bvyo-f3df0',
    storageBucket: 'bvyo-f3df0.firebasestorage.app',
    iosBundleId: 'com.example.bvyoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW3XtSb8kEhLSiBCRohWr6-sa9lO9H1x4',
    appId: '1:408689466375:ios:f1de2fcf4149d06d079ea2',
    messagingSenderId: '408689466375',
    projectId: 'bvyo-f3df0',
    storageBucket: 'bvyo-f3df0.firebasestorage.app',
    iosBundleId: 'com.example.bvyoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSsPAqlvQmpoZvu6xLkjBuK3OxM_8dQhY',
    appId: '1:408689466375:web:e17c0248612c2572079ea2',
    messagingSenderId: '408689466375',
    projectId: 'bvyo-f3df0',
    authDomain: 'bvyo-f3df0.firebaseapp.com',
    storageBucket: 'bvyo-f3df0.firebasestorage.app',
    measurementId: 'G-18BN3JWQNL',
  );
}