name: flutter_bvyo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  webdav_client: ^1.1.3
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  http: ^1.1.0   # WebDav veya HTTP bağlantılarını yönetmek için
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_auth: ^4.15.3
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.0
  google_sign_in: ^6.1.6

  path: ^1.8.3
  path_provider: ^2.1.2
  mime: ^1.0.4

  # Eklemen gereken kütüphaneler:
  google_fonts: ^6.1.0
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bvyo-f3df0-3fb89df0ad47.json
    - assets/images/
    - assets/


